### PR TITLE
Add error handling for SQL syntax error

### PR DESCRIPTION
**Pull request by odininon**
Handles #2.

Hopefully, this is somewhat in the direction you are looking for.

### CODE REVIEW

**Comment by kdabir** [comment]
Wow this was pretty quick.  Thank you so much for contributing. 

A small observation: as I keep the console open to see the output, the error text div is hidden and I don't get feedback that query failed. 

image

Once I scroll, then I see 
image

I think this will be automatically solved when #1 is implemented, till then we can notify in console as well about the failure.

**Comment by odininon** [comment]
Will attempt #1 when I get home from work, if it’s still open. I will also add the useful information into the console as well.

**Comment by odininon** [comment]
Just saw someone else wanted to work on it. I’ll just add the information back to the console for errors :)

**Comment by kdabir** [comment]
No worries, eventually I would want to get rid of the console based output and have all data shown and updated in the UI. The results grid is going to be one of the challenging part. You may also collaborate the with other person to review the PR. Thanks again for the interest and extending help.

**Comment by odininon** [comment]
Not a problem :) Gives me a chance to practice my react without having to think of my own projects.

**Pull request merged**
